models/spider_model.py
import os

from sqlalchemy import Sequence
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, DateTime, Date


# 乱码
os.environ['NLS_LANG'] = 'SIMPLIFIED CHINESE_CHINA.UTF8'
# 创建对象的基类
Base = declarative_base()


# 产品类别链接
class StarInfo(Base):
    __tablename__ = 'star_photos'

    id = Column(Integer, Sequence('seq_star_photos'), primary_key=True, autoincrement=True)
    star = Column(String(64), nullable=True, comment='明星')  # 明星
    release_time = Column(Date, nullable=True, comment='照片发布时间')  # 照片发布时间
    star_img_path = Column(String(3000), nullable=True, comment='照片地址')  # 照片地址
    star_url = Column(String(3000), nullable=True, comment='图片链接地址')  # 图片链接地址
    star_update_time = Column(DateTime, nullable=True, comment='照片更新时间')  # 照片更新时间

models/web_models.py
from extensions import db


class WebStarInfo(db.Model):
    __tablename__ = 'star_photos'

    id = db.Column(db.Integer, primary_key=True)
    star = db.Column(db.String(64), nullable=True, comment='明星')
    release_time = db.Column(db.Date, nullable=True, comment='照片发布时间')
    star_img_path = db.Column(db.String(3000), nullable=True, comment='照片地址')
    star_url = db.Column(db.String(3000), nullable=True, comment='图片链接地址')
    star_update_time = db.Column(db.DateTime, nullable=True, comment='照片更新时间')

views.py
import datetime
from logs import web_log_info
from db.db_mysql import session, func
from models.spider_model import StarInfo
from models.web_models import WebStarInfo
from flask import Blueprint, render_template, redirect, url_for, request


from utility.util_config import get_config_value
from utility.util_star_map import star_pinyin_dict, star_name_dict, encode_name, decode_name


star = Blueprint('star', __name__)


# 蓝本配置元组
DEFAULT_BLUEPRINT = (
    # 蓝本 前缀
    (star, '/'),
    (star, '/star'),
    (star, '/star/date')

)

star_list = get_config_value('STAR_INFO', 'STAR_LIST').split(',')
time_str = (datetime.datetime.today() - datetime.timedelta(1)).__format__('%Y-%m-%d')


# 蓝本启动配置
def config_blueprint(app):
    for blue_print, url_prefix in DEFAULT_BLUEPRINT:
        app.register_blueprint(blue_print, url_prefix=url_prefix)


# 404
def config_errorhandler(app):
    @app.errorhandler(404)
    def page_not_found(e):
        data = {'star_dict': {name: encode_name(name) for name in star_list}}
        return render_template('error404.html', **data)


@star.route('/')
def index():
    return redirect(url_for('star.show_star'))


@star.route('/star')
def show_star():

    star_db = session.query(StarInfo.star, func.count(StarInfo.star)).group_by(StarInfo.star).order_by(
        func.count(StarInfo.star).desc()).all()[:3]

    img_path_list = [session.query(StarInfo.star_img_path).filter(StarInfo.star == name).first()[0]
                     for name, _ in star_db]
    data = {
        'star_dict': {name: encode_name(name) for name in star_list},
        'star_name': [star_pinyin_dict[name] for name, _ in star_db],
        'img_path_list': img_path_list,
        'encode_name': [encode_name(star_pinyin_dict[name]) for name, _ in star_db],
    }

    return render_template('index.html', **data)


@star.route('/star/<name>', methods=['GET'])
def show_star_one(name):
    return redirect(url_for('star.show_star_page', name=name, page=1))


@star.route('/star/<name>&<page>', methods=['GET'])
def show_star_page(name, page):
    data = {
        'name': name,
        'star_dict': {name: encode_name(name) for name in star_list}
    }
    try:
        name_pinyin = star_name_dict[decode_name(name)]
    except Exception as e:
        web_log_info('error-------show_star_page :{}'.format(e))
        return render_template('error404.html', **data)

    img_date_list = session.query(StarInfo.star_img_path, StarInfo.release_time).filter(
        StarInfo.star == name_pinyin).order_by(StarInfo.star_update_time.desc()).limit(6).offset((int(page)-1)*6).all()

    data['name_ch'] = decode_name(name)
    data['url_date'] = [_ for _ in img_date_list]
    paginate = WebStarInfo.query.filter(WebStarInfo.star == name_pinyin).paginate(
            page=int(page), per_page=6, error_out=False)
    data['paginate'] = paginate
    # print(paginate)

    return render_template('star_page.html', **data)


@star.route('/star/date', methods=['GET', 'POST'])
def show_images_for_time():
    data = {
        'star_dict': {name: encode_name(name) for name in star_list}
    }
    try:
        if request.method == 'POST':
            page = request.args.get('page', 1)
            select_date = request.form.get('time', None)
            if select_date is None or datetime.datetime.strptime(select_date, '%m/%d/%Y %H:%M %p') > (
                    datetime.datetime.today() - datetime.timedelta(1)):
                select_date = time_str
            else:
                select_date = datetime.datetime.strptime(select_date, '%m/%d/%Y %H:%M %p').__format__('%Y-%m-%d')

            data['select_date'] = {'select_date': select_date, 'encode': encode_name(select_date)}

        else:
            page = request.args.get('page', 1)
            select_date = decode_name(request.args.get('date', None)) \
                if request.args.get('date', None) else None

            data['select_date'] = {'select_date': select_date, 'encode': encode_name(select_date)} \
                if select_date else {'select_date': None}
            print(data['select_date'])
        if data.get('select_date').get('select_date') is None:
            data['select_date'] = {'select_date': None}
            img_date_list = session.query(StarInfo.star_img_path, StarInfo.release_time, StarInfo.star).order_by(
                StarInfo.star_update_time.desc()).limit(6).offset((int(page) - 1) * 6).all()
            paginate = WebStarInfo.query.paginate(page=int(page), per_page=6, error_out=False)
        else:
            img_date_list = session.query(StarInfo.star_img_path, StarInfo.release_time, StarInfo.star).filter(
                StarInfo.release_time == select_date).order_by(StarInfo.star_update_time.desc()).limit(6).offset(
                (int(page) - 1) * 6).all()
            paginate = WebStarInfo.query.filter(WebStarInfo.release_time == select_date).paginate(
                page=int(page), per_page=6, error_out=False)
            data['select_date'] = {'select_date': select_date, 'encode': encode_name(select_date)}
        data['paginate'] = paginate
        data['url_date_star'] = [[url, date, star_pinyin_dict[_]] for url, date, _ in img_date_list]
    except Exception as e:
        web_log_info('error---------select data by date error: {}'.format(e))

    return render_template('date_page.html', **data)

templates/date_page.html
{% extends "bootstrap/base.html"  %}
{% import 'bootstrap/wtf.html' as wtf %}
{%- block head %}
<title>秒优大数据</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="../static/imgs/mu.png">

{%- block styles %}
<!-- Bootstrap -->
<link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
<!-- Bootstrap core CSS -->
<!-- bb——这里是通过下载网页上的css文件，保存在static目录下即可-->
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css"
      rel="stylesheet">

<!-- Custom styles for this template -->
{%- endblock styles %}
{%- endblock head %}

{% block body -%}
{% block navbar %}
<div class="navbar-wrapper">
    <div class="container" style="width: auto">

        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container" style="width: auto">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/star" style="padding: 15px 30px">秒优大数据</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        {% for name, en_name in star_dict.items() %}
                        <li>
                            <a href="/star/{{en_name}}">{{name}}</a>
                        </li>
                        {% endfor %}
                        <li>
                            <a href="/star/date">按时间</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </div>
</div>

{%- endblock navbar %}
{% block content -%}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading text-center"
                 style="background-color: #ffffff; border-color: #ffffff; color: #0f0f0f">
                {%if select_date.select_date %}
                <h3>{{select_date.select_date}}的图片</h3>
                {%else%}
                <h3>全部的图片</h3>
                {%endif%}
            </div>
            <form enctype="json/plain" method="post" action="{{url_for('star.show_images_for_time')}}" class="form-inline">
                <div class="form-group col-md-5 col-md-offset-5" >
                    <div class="input-group" id="datetime">
                        <input type="text" class="form-control" name="time">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-th"></i>
                    </span>
                    </div>
                    <button type="submit" class=" btn btn-primary" style="left: 10%">查询</button>
                </div>

            </form>

            <div class="panel-body">
                {% for url, date, star in url_date_star%}
                <div class="col-sm-12">
                    <div class="thumbnail">
                        <img src=".{{url}}" alt="...">
                        <div class="caption" style="text-align: center">
                            <h3>{{star}}</h3>
                            <h4>{{date}}</h4>
                            <h3>标签栏</h3>
                            <!--                        <p>文字说明</p>-->
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>


            <nav aria-label="Page navigation" style="text-align: center">
                <ul class="pagination" style="font-size: 30px">
                    {% if not paginate.has_prev %}
                    <li class="disabled">
                        <a aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% else %}
                    <li>
                        {% if not select_date.encode %}
                        <a href="{{url_for('star.show_images_for_time', page=paginate.prev_num)}}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                        {% else%}
                        <a href="{{url_for('star.show_images_for_time', page=paginate.prev_num, date=select_date.encode)}}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                        {% endif %}
                    </li>
                    {% endif %}
                    {% for page in paginate.iter_pages(1,1,3,1) %}
                    <!--                    <p>{{num}}</p>-->
                    <li {% if page== paginate.page %} class="active" {% endif %}>
                        {%if page%}
                        {% if not select_date.encode %}
                    <li class="page-item {%if page==paginate.page%}active{%endif%}">
                        <a class="page-link" href="{{url_for('star.show_images_for_time', page=page)}}">{{page}}</a>
                    </li>
                    {%else%}
                    <li class="page-item {%if page==paginate.page%}active{%endif%}">
                        <a class="page-link" href="{{url_for('star.show_images_for_time', page=page, date=select_date.encode)}}">{{page}}</a>
                    </li>
                    {%endif%}
                    {%else%}
                    <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
                    {%endif%}


                    {% endfor %}
                    {% if not paginate.has_next %}
                    <li class="disabled">
                        <a aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% else %}
                    {% if not select_date.encode %}
                    <li>
                        <a href="{{url_for('star.show_images_for_time', page=paginate.next_num)}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {%else%}
                    <li>
                        <a href="{{url_for('star.show_images_for_time', page=paginate.next_num, date=select_date.encode)}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{%-endblock content%}


{% block scripts %}


<script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
<script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
<script src="../static/js/jquery.min.js"></script>
<script src="../static/js/bootstrap.min.js"></script>
<script src="https://cdn.bootcss.com/moment.js/2.22.1/moment-with-locales.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script>
    $("#datetime").datetimepicker();
</script>
{%- endblock scripts %}

{%- endblock body %}

templates/error404.html
{% extends "bootstrap/base.html"  %}
{%- block head %}
<title>秒优大数据</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="../static/imgs/mu.png">

{%- block styles %}
<!-- Bootstrap -->
<link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
<!-- Bootstrap core CSS -->
<!-- bb——这里是通过下载网页上的css文件，保存在static目录下即可-->
<link href="static/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom styles for this template -->
<!-- bb——这里是通过下载网页上的css文件，保存在static目录下即可-->
<link href="static/css/carousel.css" rel="stylesheet">
{%- endblock styles %}
{%- endblock head %}

{% block body -%}
{% block navbar %}
<div class="navbar-wrapper">
    <div class="container" style="width: auto">
        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container" style="width: auto">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/star" style="padding: 15px 30px">秒优大数据</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        {% for name, en_name in star_dict.items() %}
                        <li>
                            <a href="/star/{{en_name}}">{{name}}</a>
                        </li>
                        {% endfor %}
                        <li>
                            <a href="/star/date">按时间</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </div>
</div>

{%- endblock navbar %}
{% block error -%}

<div style="text-align: center;">
    <h2 >大哥，好像是你自己搞错了吧，臣妾找不到啊</h2>
    <div class="container">
        <img src="../static/imgs/404.jpg" class="img-responsive" style="display: inline;">
    </div>
</div>
{%-endblock error%}

{% block scripts %}
<script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
<script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{#
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>#}
<script src="/static/js/jquery.min.js"></script>

<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
{#
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
<script src="/static/js/bootstrap.min.js"></script>


{%- endblock scripts %}

{%- endblock body %}

templates/form_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
<!-- Bootstrap core CSS -->
<!-- bb——这里是通过下载网页上的css文件，保存在static目录下即可-->
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css"
      rel="stylesheet">
</head>
<body>
<form enctype="json/plain" method="post" action="{{url_for('star.show_images_for_time')}}" class="form-inline">
                <div class="form-group col-md-5 col-md-offset-5" >
                    <div class="input-group" id="datetime">
                        <input type="text" class="form-control" name="time">
                    <span class="input-group-addon">
                        <i class="glyphicon glyphicon-th"></i>
                    </span>
                    </div>
                    <button type="submit" class=" btn btn-primary" style="left: 10%">查询</button>
                </div>

            </form>

</body>
<script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
<script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
<script src="../static/js/jquery.min.js"></script>
<script src="../static/js/bootstrap.min.js"></script>
<script src="https://cdn.bootcss.com/moment.js/2.22.1/moment-with-locales.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
<script>
    $("#datetime").datetimepicker();
</script>
</html>

templates/star_page.html
{% extends "bootstrap/base.html"  %}
{%- block head %}
<title>秒优大数据</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="../static/imgs/mu.png">

{%- block styles %}
<!-- Bootstrap -->
<link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
<!-- Bootstrap core CSS -->
<!-- bb——这里是通过下载网页上的css文件，保存在static目录下即可-->
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom styles for this template -->
{%- endblock styles %}
{%- endblock head %}

{% block body -%}
{% block navbar %}
<div class="navbar-wrapper">
    <div class="container" style="width: auto">

        <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container"  style="width: auto">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/star" style="padding: 15px 30px">秒优大数据</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        {% for name, en_name in star_dict.items() %}
                        <li>
                            <a href="/star/{{en_name}}">{{name}}</a>
                        </li>
                        {% endfor %}
                        <li>
                            <a href="/star/date">按时间</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </div>
</div>

{%- endblock navbar %}
{% block content -%}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading text-center" style="background-color: #ffffff; border-color: #ffffff; color: #0f0f0f">
                <h3>{{name_ch}}图片</h3>
            </div>
            <div class="panel-body">
                {% for url, date in url_date%}
                <div class="col-sm-12" >
                    <div class="thumbnail">
                        <img src=".{{url}}" alt="...">
                        <div class="caption" style="text-align: center">
                            <h3>{{date}}</h3>
                            <h3>标签栏</h3>
<!--                        <p>文字说明</p>-->
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>


            <nav aria-label="Page navigation" style="text-align: center">
                <ul class="pagination" style="font-size: 30px">
                    {% if not paginate.has_prev %}
                    <li  class="disabled">
                        <a aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{{url_for('star.show_star_page', name=name, page=paginate.prev_num)}}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif  %}
                    {% for page in paginate.iter_pages(1,1,3,1) %}
<!--                    <p>{{num}}</p>-->
                    <li {% if page == paginate.page %} class="active"{% endif  %}>
                    {%if page%}
                        <li class="page-item {%if page==paginate.page%}active{%endif%}">
                            <a class="page-link" href="{{url_for('star.show_star_page', name=name, page=page)}}">{{page}}</a>
                        </li>
                    {%else%}
                        <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
                    {%endif%}


                    {% endfor  %}
                    {% if not paginate.has_next %}
                    <li  class="disabled">
                        <a aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{{url_for('star.show_star_page', name=name, page=paginate.next_num)}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif  %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{%-endblock content%}

{% block scripts %}
<script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
<script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>


<script src="../static/js/jquery.min.js"></script>

<script src="../static/js/bootstrap.min.js"></script>


{%- endblock scripts %}

{%- endblock body %}